name: list_in_aja
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.2.2 
  timezone: ^0.9.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.1
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_lints: ^5.0.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/LogoOnly.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/LogoOnly.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/LogoOnly.png
    - assets/images/TextOnly.png
